🎉 initial commit

diff --git a/bin/install b/bin/install
--- a/bin/install
+++ b/bin/install
@@ -1,25 +1,37 @@
 #!/usr/bin/env bash
 
-# redsymbol.net/articles/unofficial-bash-strict-mode/
-set -o nounset -o pipefail -o errexit
-IFS=$'\n\t'
+set -e
+set -o pipefail
 
-get_tmpdir() {
-  local tmpdir
+[ -n "$ASDF_INSTALL_VERSION" ] || (>&2 echo 'Missing ASDF_INSTALL_VERSION' && exit 1)
+[ -n "$ASDF_INSTALL_PATH" ] || (>&2 echo 'Missing ASDF_INSTALL_PATH' && exit 1)
 
-  set +o nounset
-  if [ "$TMPDIR" = "" ]; then
-    tmpdir="$(mktemp -d -t bazel_build_XXXXXX)"
-  else
-    tmpdir="$TMPDIR"
+check_install_type() {
+  local install_type="$1"
+  if [ "$install_type" != "version" ]; then
+    echo -e "\nThe asdf-bazel plugin only supports installing official, tagged"
+    echo "releases as released by the Bezel team on Github:"
+    echo "https://github.com/bazelbuild/bazel/releases"
+    echo -e "\nIf you wish to install another version from source, see: "
+    echo "https://docs.bazel.build/versions/master/install.html"
+    exit 1
   fi
-  set -o nounset
-
-  echo "$tmpdir"
 }
 
-get_platform() {
-  uname | tr '[:upper:]' '[:lower:]'
+get_platform () {
+	local platform="$(uname | tr '[:upper:]' '[:lower:]')"
+
+	case "$platform" in
+		linux|darwin|freebsd)
+			echo "Platform '${platform}' supported!" >&2
+			;;
+		*)
+			echo "Platform '${platform}' not supported!" >&2
+			exit 1
+			;;
+	esac
+
+	echo -n ${platform}
 }
 
 get_installer_name() {
@@ -35,33 +47,32 @@ get_installer_url() {
   echo "$url_base/$version/$installer_name"
 }
 
-check_install_type() {
-  local install_type="$1"
-  if [ "$install_type" != "version" ]; then
-    echo -e "\nThe asdf-bazel plugin only supports installing official, tagged"
-    echo "releases as released by the Bezel team on Github:"
-    echo "https://github.com/bazelbuild/bazel/releases"
-    echo -e "\nIf you wish to install another version from source, see: "
-    echo "https://docs.bazel.build/versions/master/install.html"
-    exit 1
+
+get_tmpdir () {
+  local tempdir=""
+  if [ "linux" = "$1" ] ; then
+    tempdir=$(mktemp -d asdf-bazel.XXXX)
+  else
+    tempdir=$(mktemp -dt asdf-bazel.XXXX)
   fi
+  echo -n $tempdir
 }
 
-install_bazel() {
+install () {
   local install_type="$1"
   local version="$2"
   local install_path="$3"
-  local tmpdir="$(get_tmpdir)"
+  local tempdir=$(get_tmpdir $platform)
   local installer_name="$(get_installer_name $version)"
-  local installer_path="$tmpdir/$installer_name"
+  local installer_path="${tmpdir}/${installer_name}"
   local installer_url="$(get_installer_url $version)"
 
-  check_install_type "$install_type"
+  check_install_type "${install_type}"
 
-  curl -L -s -o "$installer_path" "$installer_url"
-  chmod u+x "$installer_path"
+  curl -L -s -o "${installer_path}" "${installer_url}"
+  chmod u+x "${installer_path}"
 
-  "$installer_path" --prefix="$install_path"
+  "${installer_path}" --prefix="${install_path}"
 }
 
-install_bazel "$ASDF_INSTALL_TYPE" "$ASDF_INSTALL_VERSION" "$ASDF_INSTALL_PATH"
+install $ASDF_INSTALL_TYPE $ASDF_INSTALL_VERSION $ASDF_INSTALL_PATH
